---
- name: Configure host
  hosts: all
  become: true
  vars:
    users:
      - username: "cloudru"
        groups: "cloudru"

  tasks:
    - name: Create groups
      group:
        name: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"

    - name: Create user accounts and add users to groups
      user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
      loop: "{{ users }}"

    - name: Allow SSH login with key for users
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'keys/' + item.username + '.pub') }}"
      loop: "{{ users }}"

    - name: Allow SSH login with key if not UBUNTU
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.reg }}"
        line: "{{ item.line }}"
      with_items:
        - { reg: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { reg: '^#?AuthorizedKeysFile', line: 'AuthorizedKeysFile     .ssh/authorized_keys' }
      notify:
        - restart sshd
      when: ansible_distribution!= "Ubuntu"

    - name: Disable SSH login for root user
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted