---
apiVersion: v1
kind: Service
metadata:
  name: cloud-ru-cluster-ip
  namespace: cloud-ru-namespace
spec:
  selector:
    app: cloud-ru-app
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
