---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ru-deployment
  namespace: cloud-ru-namespace
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: cloud-ru-app
          image: suntrackspb/cloud-ru-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
      restartPolicy: Always